apiVersion: v1
kind: Service

metadata:
  name: turbine-mlops-service

spec:
  type: NodePort

  selector:
    app: turbine-mlops

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080